// Vignettes, part A (from Chapter One)
const CITIES_A = [
{ id:"dannels-pride", cat:"memory", place:"dannels-pride", title:"Dannel's Pride", body:[
"Dannel's Pride is a ward of crowded rooms inside a giant's ruin, and every room holds a piece of Cyre bought at a price no one in the room could afford. A teacup with its crack mended in gold. A regimental button. A hymnal with a stranger's mother's name on the flyleaf. A door-knocker that hung, the seller swears, on a house near the old palace. Families that have not eaten meat since spring pool their coins for these, and set them on the sill where the light is best.",
"Ask what Cyre was and each refugee answers with one city. There is the Cyre of lamps, where the streets stayed lit all night by order of a queen. There is the Cyre of orchards, which smelled of pears for a month every autumn. There is the Cyre of one bakery on one corner, and the Cyre of a ferry crossing at dusk, and the Cyre of a grandmother's kitchen with the shutters half closed. Laid side by side these cities share no border and no road.",
"The old keep buying. The young have stopped. In the back rooms a militia called Dannel's Wrath keeps a different collection, of scrolls with fire folded into them, and the young bring their coins there. Both collections are called Cyre, and the people who tend them pass each other on the stairs every morning and nod."
]},
{ id:"stone-heads", cat:"memory", place:"stone-heads", title:"The Stone Heads", body:[
"You will find them in every district, in threes and fours, leaning on walls, teetering on ledges, lying in the gutter with one ear in the mud. They are the heads of giants, broken from statues too large to reassemble, each with its own braids and its own expression. You will be told never to quarry one, because of a curse. The city, which sells its own graves, leaves them alone.",
"The old people will tell you that the faces have changed. The one by the fish stalls was smiling in their grandmothers' day; now a lip has drawn back from the teeth. In this account the heads remember the city the giants intended and compare it, year after year, with the one in front of them, and their opinion of the comparison shows a little more each year.",
"You will watch one for an afternoon and see nothing move. Toward evening a woman will come with a rag and a bowl and clean the lichen out of its eyes, and set a pickled apple on its lower lip, and go home. If you ask her why, she will look at you the way you would look at someone who asked why you wash your own face."
]},
{ id:"hammersmiths", cat:"memory", place:"hammersmiths", title:"Hammersmith's Inn", body:[
"Forgelight is loud and its people are quiet. The furnaces roar, the yards of House Deneith ring with drill, and the men and women of the district go through it all saying as little as they can, as if words were rationed. They spend the ration at Hammersmith's Inn. In the evenings its long tables fill with veterans of the Last War, seated without regard to flag. A Karrn sits beside a Brelish sapper. An Aundairian war-wizard pours for the Thrane who once tried to burn her. Two years ago, they will tell you, they would have knifed each other on sight. Now the custom is a toast. Someone stands and names a battle, and everyone who was there, on any side, drinks to the dead of that day, and then someone else stands and names another. The war was long and the list has never run out. In the morning they oil their blades and sign on with a Deneith captain to guard a dig in the jungle. I asked a sergeant what he would do once every battle had been toasted. He looked at the empty glass in my hand for some time, and said it was my round."
]},
{ id:"bazaar", cat:"desire", place:"bazaar", title:"The Bazaar", body:[
"Over the Marketplace stands a tent so large that the sun, coming through it, makes a second and redder sky. It has been patched and dyed so often that its first color is a matter of dispute. In that light every face looks flushed and every blade looks warm.",
"Under it you may buy, for one gold piece, your own face in soapstone, carved by a blind half-orc who learns it with her fingers. For a few silver you may buy a strip of cloth soaked at last Sar's executions, priced by the fame of the man who bled on it. For twenty gold, a map of the floor of the Thunder Sea; for two hundred, a map of Kythri, where nothing holds its shape long enough to be mapped. A gnome named Hanruli sells tapestries she dreamed, and in one of them you will find yourself impaled on the railing of a black tower beside a stormy sea. She is as frightened of the likeness as you are. She will still sell it to you.",
"The traders here would sell their mothers, the saying goes, and they compete for the privilege. Very little in the bazaar is false and nothing is cheap. Each stall prices its goods by how badly you want them, and the sellers have had generations to learn to read wanting. Under the red cloth you cannot see how pale a buyer goes when he counts out the coins."
]},
{ id:"shadows", cat:"desire", place:"shadows", title:"Shadows", body:[
"There is a house in Locksmith Square whose address nobody will give you. To find it you must first find someone who knows a word, which costs money, and then that person will ask you what shadows seek. The answer is illumination. Everyone who has been inside knows it, and repeats it to no one.",
"If you answer, and the person likes the look of you, you receive directions and a second word, which changes so often that last month's is worthless. Inside, the elves of House Thuranni pour the finest spirits in Xen'drik in rooms with low lamps, and you tell them what you desire, and in a little while it comes up the stairs. Later, in the dark, you tell them other things. Most clients remember nothing of what they said in the dark. The few who remember trust the house to keep it, and it does, somewhere that has no address either.",
"The elves keep no enclave in Stormreach and take no side among the lords. When a man with powerful enemies disappears, people sometimes mention the house, and then they talk about the weather."
]},
{ id:"pirates-moon", cat:"desire", place:"harbor-docks", title:"Pirate's Moon", body:[
"On the twentieth of Dravago the whole city walks down to the water carrying things. Bread, rings, coins, a roast fowl, ribbons, a letter that was never sent. At the end of the piers they throw it all into the harbor, and the sahuagin watching from the swells let it sink.",
"The offerings are for the Devourer. In the city's first hard years the pirate lord Jaldrin Arekarn and his beloved, the dread captain Kilen Razorheart, broke an invading armada in this harbor, and as they embraced over the victory a traitor's arrow found them both. They went over the side together and were never found. The city feeds the god every spring so that he will leave the lovers alone. Jaldrin had no children. If he had, they would sit among the Storm Lords now.",
"It is also the festival of love. The young court each other on the piers while the gifts go down around them, and some cut their palms and press them together, which is the strongest promise Stormreach knows. Late in the evening I watched a girl throw in a sealed letter, wait until it darkened and turned under, then take her young man by the hand and lead him quickly away from the edge, as if the sea might ask for a reply."
]},
{ id:"black-wrack", cat:"signs", place:"black-wrack", title:"The Black Wrack", body:[
"The north wall of the Black Wrack, which calls itself the biggest tavern in Stormreach, cannot be seen. Notices cover it, nailed over notices, and the landlord, a large good-natured man everyone calls Brick, sorts them by kind. His rule is that all are welcome and every quarrel goes outside. His mastiff, Sascha, walks a slow circuit of the floor, and no drinker, however drunk, involves her in anything. Here is the wall as it stood on one evening.",
"<em>Guide wanted. Must speak Giant. No pay in advance.</em> <em>Lost, one brother, last seen at the Tents. Red beard. Owes me money.</em> <em>Strong backs for a short dig. No questions.</em> <em>Will buy any map, any condition. Will pay ten times as much for a true one.</em> <em>Wanted, anyone who has come back from the Cinder Sisters. Only to talk.</em> <em>Found, one hand, with ring. Ask at the bar.</em>",
"The ceiling is high enough for the minotaur Kolos to stand upright, and on most nights he stands in front of the wall with a cup and reads it from top to bottom. He has never answered a notice. When Brick asked him why he bothered, he said he was checking whether any of them were about him."
]},
{ id:"circle-of-visions", cat:"signs", place:"circle-of-visions", title:"The Circle of Visions", body:[
"Twelve rings of standing stones are scattered through the city, and none of the people who raised them are alive. About once a month, on a night no almanac predicts, a picture rises in the middle of one ring and hangs there until dawn. Sometimes it is a garden. Sometimes it is a giant whose name has been lost, standing as if about to speak. Sometimes it is a stretch of jungle where, the scholars say, the giants or their enemies kept an outpost. Sometimes it is something that frightens the children, and the priests call it a warning, and the fortune-tellers sell the warning back to the people who saw it.",
"Lately an old hill giant from the Tents walks from ring to ring at dusk with a staff and a basket of herbs, and sits with his back against the stones, and waits. His name is Gaulronak. He has lived beside this city for nearly two hundred years, and he is patient in the manner of someone who expects to outlast the question.",
"I sat with him one night in the ring in the Marketplace. Nothing came. Toward morning I asked what the pictures were for. He said the carvers had known they would forget, and had made the stones remember for them. Then he said the stones were never told which memories mattered, so they show all of them at the same rate, the gardens and the warnings alike, once a month, to whoever happens to be sitting there."
]},
{ id:"tattered-alice", cat:"signs", place:"fishers-folly", title:"Tattered Alice", body:[
"In Fisher's Folly, among the nets and the leaning huts, a woman called Tattered Alice tears at her clothes with her nails and shouts what is coming. Dark gods will wake under the harbor. The sea devils will rise in a plague. The Storm Lords will poison the water. She has shouted for years, and not one of her prophecies has come true. Anywhere else this would make her a madwoman. The fishers of the Folly have drawn the opposite conclusion, which is that each disaster, once Alice has said it aloud, is used up and can no longer happen. So before a hard voyage they bring her fish heads and a coin, sit on an upturned hull at her feet, and ask her to name the worst. She names it. They thank her. They go out past the Talon in weather that would keep a Lyrandar captain in port, and most of them come back, and nobody in the Folly thinks this proves anything except what they knew already. The only thing they fear is the morning Alice wakes up hoarse."
]},
{ id:"rigging", cat:"rigging", place:"cross", title:"The Rigging", body:[
"To cross Stormreach you will need your hands. The city was built for people four times your height, and the people who live in it now have had to rig it, like a ship, before they could sail it. Where a step comes up to your chest, someone has cut a smaller step into it. Where a wall has no door, someone has hung a knotted rope. Over Cross the rope bridges run so thickly from ruin to ruin that the sky comes down in strips, with laundry hanging in them.",
"Learn the colors. New hemp is gold and will hold you. Grey hemp has seen a few wet seasons and will probably hold you. Black hemp is older than anyone's grandmother, and only those who were born on it walk on it; they will pass you at a run while you are still deciding. Learn also that some houses hang from the undersides of floating stones, that their owners draw up the ladders at night and sleep swaying, and that if you call up to them after dark nobody will answer.",
"There are people in Cross who have not set foot on the giants' pavement in years. Ask them the way to the Marketplace and they will point up."
]},
{ id:"leaky-dinghy", cat:"rigging", place:"fishers-folly", title:"The Leaky Dinghy", body:[
"Fisher's Folly is a heap of boats, poles, huts and nets lashed together at the harbor's edge so that each holds up the others, and in the middle of the heap stands a tavern called the Leaky Dinghy. It rots. Rats run in its rafters. The floor leans east in the morning and west by night. Sahuagin come in out of the rain to be hired as guides across the Thunder Sea, and the kitchen serves them dishes that are raw and still moving, which the very drunk sometimes order as well, and regret.",
"By every reckoning the building should have gone down years ago. Its regulars will not allow it. They patch it after each storm with whatever the storm brought in, and during the worst storms, when shingles are coming off the Harbormaster's house up the hill, they crowd inside and hold a party. They drink to the beams by name. They cheer every gust that fails. When the wind finally drops they go out along the swaying planks to see what is missing, and if it is only a little they look faintly disappointed."
]},
{ id:"rubble-warren", cat:"rigging", place:"rubble-warren", title:"The Rubble Warren", body:[
"Nobody in Stormreach quarries stone. The giants left more than any city could use, and the people of the present break it up and carry it off. On the northern edge of Saltire there is a field where the blocks are broken, and it is called the Rubble Warren. Bees have hived in its cracks, and their honey goes into the little cakes sold at a stall in the Sloths.",
"The children of the ward have dug tunnels through the broken stone and given them names. A twelve-year-old called Cadroc leads a band of them who mean to be explorers. They practice with wooden swords and keep a map of the Warren in chalk on a flat slab at its center, and Cadroc will tell you very seriously which tunnels are dangerous. Every month the stone-breakers cart off a few more blocks for some wall in Cross, and a tunnel goes with them, and the boys rub it off the slab and draw in the new ones.",
"I crawled through one tunnel at Cadroc's invitation. Its walls had been the floor of a giant's house, and before that a quarry the giants cut, and next year they will be the wall of a boarding house in Cross, and after that, when the boarding house falls, rubble again, for children who are not yet born to dig through and name."
]},
{ id:"harbor", cat:"trade", place:"harbor", title:"The Harbor", body:[
"Everything in Stormreach runs downhill into the harbor. Rain goes down, and sewage, and rumor, and the blood from the Marketplace on Sar, and now and then a man who owed money to the Bilge Rats, and the outflow of the Waterworks, which the gulls do not seem to mind. The water smells like a ledger in which all of it has been entered. On the piers a hill giant and two orcs of House Tharashk load dragonshards onto a Lyrandar ship. A goblin haggles with two elves of Aerenal over a crate wrapped in leaves. A dwarf in the robes of the Sovereign Host and a human in the silver of the Flame argue doctrine with a sahuagin priest who wears seaweed and the bones of something large. The hobgoblins on the slave ships do not look up. The guard at the end of the pier does not look at anyone.",
"Coin from every mint in the world crosses these planks, and none of it is asked where it has been. In a city of pirates, they say, all tender is legal. The scales at the duty-house are honest. The man who reads them, Berrigan Enge, a distant cousin of the Harbor Lord, skims so steadily and for so long that the merchants have built him into their prices, like the weather. A loaf in Cross costs a little more because of him. Everyone in Cross knows exactly how much."
]},
{ id:"von-ruthveks", cat:"trade", place:"von-ruthveks", title:"Von Ruthvek's Splendors of the South", body:[
"A clay tablet the size of a door comes into Stormreach on the shoulders of four porters and is carried up to the shop of Valexa Von Ruthvek, a gnome who keeps her stock in labeled cases like a museum and can date a broken lamp by the wear on its handle. She dates the tablet to the Age of Giants. Two of the expedition that found it did not come back, and she adds a line for each to the card that will travel with it, in small upright letters.",
"In a cellar across the city a second tablet the size of a door is drying on trestles. Its clay was dug from the riverbank on Wir. A journeyman of the Hollow Shards has aged it with cold tea and a hot iron, and a senior forger is cutting the last line of an inscription in a Giant that has not been spoken for forty thousand years and that he speaks rather well. It will be more beautiful than the first. Several of its elder brothers stand in warded cases at Morgrave University under labels that call them landmark discoveries, and on holidays the forgers take their apprentices to look.",
"Von Ruthvek's expeditions are paid for now by patrons she has never met, through intermediaries, on one condition, that each go deeper into the wilds than the last. She does not know why. Each comes home with less, and with fewer of the people who went, and the cards she writes to travel with what they bring grow longer every season."
]},
{ id:"tents-of-rusheme", cat:"trade", place:"tents-of-rusheme", title:"The Tents of Rushemé", body:[
"Across the river from Southwatch the giants keep their market. The tents are as tall as houses, and the people of the city walk among them like children among furniture. Herbs are sold there, and hides and resins, and the right to follow a giant into the jungle as a guide. The giants are nomads of several tribes, mostly hill and jungle giants, and they come to this border to trade, to keep their rites, and to be near the city that belonged to their ancestors. They are careful with the people who live in their ancestors' houses. They are not friendly.",
"On certain nights, at sunset, they sing. In Southwatch people stop what they are doing. The sound arrives through the soles of the feet before the ears have it. A Karrn woman on her doorstep told me she had lived beside the Tents for eleven years and had never asked what the songs were about, and did not mean to. She went in before the end. Her neighbors stayed out until the last note, and then they went in too and closed the shutters on the river side, which they do not do on other nights."
]},
{ id:"silverwall", cat:"eyes", place:"locksmith-square", title:"Locksmith Square", body:[
"The walls around Locksmith Square rise sixty feet and shine like silver on the side that faces the square, and only on that side; from the streets outside they are grey stone. Inside, you are seen twice. Your lantern goes away from you along the walls in both directions. The acrobat above the crowd tumbles above herself. When the Red Ring lets out after a bloody match, the crowd leaving the arena is joined by a second crowd, blurred and bright, leaving with it. The reflections are never clear enough to show you your own face. They are clear enough to show you that someone is watching, that the someone has turned your way, and that you have turned to watch them back. At night the silver spreads every lamp thin and doubles every shadow. Pickpockets love it. So do lovers, and so do brawlers, who know that the Guard will let them fight here as it would never let them fight in Respite. Stand still long enough in the middle of the square and you will notice that you have begun to walk the way the people who live there walk, with your head a little turned, as if listening to someone at your shoulder."
]},
{ id:"eldreds-pool", cat:"eyes", place:"eldreds-pool", title:"Eldred's Pool", body:[
"At the center of Locksmith Square there is a basin of dark green stone, twenty-four feet across, from which the ward draws its water. Whatever is poured into it comes out clean. Rain, bilge, wine and poison all come out the same. In the middle two six-limbed figures stand back to back, each balanced on one leg, one pair of hands pressed flat together, the other pair raised to hold up something that is not there. Their stone heads are bowed.",
"The thri-kreen made it. Tens of thousands of them lived here once, carving tunnels into the giants' foundations, and then, as far as anyone can tell, they were all gone at the same moment. In the city's first years a scholar named Eldred grew obsessed with the basin. He paid ruffians to chip at it and bring him samples of its water. At last he went to the Storm Lords and demanded that they destroy it, because, he said, it endangered everyone. They asked for proof. He had none he would say aloud, and they sent him away. By the next day he had vanished.",
"The few who know such things say the pool sends home anything that does not belong to this world, if the thing sees its own reflection in the water. The Riedran consul warns the Inspired among his countrymen to look away when they pass. I filled a cup there every morning while I lodged in the square, and looked down each time, and each time the water showed me the same tired traveler under the two bowed heads, and left him where he was."
]},
{ id:"red-ring", cat:"eyes", place:"red-ring", title:"The Red Ring", body:[
"The magistrates of Stormreach have two sentences for serious crimes. One is death, carried out on Sar in the square at the foot of the palace steps, with families bringing their lunch. The other is the Red Ring, where a convict may fight his way out; win a title bout and the city paroles you. The stands fill every night. Sailors, refinery hands, adventurers, magistrates and the occasional Storm Lord all bet. Some of the fighters are convicts and some are volunteers. Some are the bloodbound, sworn to the arena for life, and it is said that the stablemasters lend them to certain lords when someone needs to die quietly.",
"I watched from the high seats as a Valenar elf ducked a giant's club to the roar of the crowd. His people tell of a hero, Dyrael Morain, who led the largest elf army ever raised against this city in the age of the giants, and died with all of it. Valenar warriors still search the fields south of Stormreach for his bones and his blade. This one had crossed the sea to stand where his ancestor fell, and he had found the place. A seat cost a copper. The club came round again."
]},
{ id:"recruiters", cat:"names", place:"recruiters", title:"The Stormreach Recruiters", body:[
"Near the palace there is an office where a man may put down his name. He signs on with the Stormreach Guard, completes three months of training, and every crime he ever committed is wiped away. The Storm Lords have handed fugitives back to the Five Nations before. They have never handed back a guard. Most recruits take a new name to mark the change, and the clerk writes it in the roll beside the old one, which is then inked over.",
"Some names from this year's roll, as the clerks recall them. Steady. Ransom. Clean. Ash, and then a second Ash, entered as Ash Again. Merit. Tomorrow. Mercy, which three women asked for in the same month. A man who could think of nothing wrote down his old name and was told that it was not allowed.",
"The Guard holds deserters and war criminals, a fallen paladin or two, and a handful who believe in the law and are made miserable by the rest. On patrol they meet their old selves in every tavern, and are not obliged to say hello. I asked one, a kind and very tired woman, what she had been called before. She said she did not remember. Then she said she remembered exactly, and that was why she had come, and that her name now was Mercy, and would I please move along."
]},
{ id:"emperor", cat:"names", place:"emperor", title:"The Emperor", body:[
"Every ship that comes to Stormreach sees it before it sees the city, and every people aboard has a name for it.",
"The scholars of Morgrave call it Cul'sir, after the titan who made this coast the heart of his empire, and write in their margins that it was set there against the demons of the past. Lyrandar pilots call it the Lamp, and line their bowsprits on the column of light that rises from its joined palms. The sahuagin have a word for it that the viceroy will translate only as <em>the dry one</em>. The wizards who have spent their lives on its aura call it, in their reports, very strong. The children of the Harbor call it the Emperor and do not ask what it ruled, and their mothers tell them it watches over them, and point.",
"Its shoulders are white with the droppings of a hundred thousand seasons of gulls. The goat path up the cliff gives out a long way below its feet, at a ledge where the goats themselves turn back, and above the ledge the grass grows to the knee, uncut and unflattened, the only grass in Stormreach that no one has walked on."
]},
{ id:"god-man", cat:"names", place:"temple-row", title:"Temple Row", body:[
"Temple Row changes every week. Priests of the Sovereign Host call out beside preachers of the Dark Six; a stall selling silver flames stands next to one selling clay figures of things that live below the world. Under the colored lanterns everyone is asking you to pray.",
"Among them, sleeping in whichever shrine is empty that night, is a man who woke from a fever knowing the names of forgotten gods. He carries them on his skin as tattoos and in his pockets as dolls, and if you stop he will introduce them. Abassa, goddess of pear cider. Zelthanon, god of cocked dice, who decides the throws that land against the wall. Humoona, goddess of lemon zest, without whom your sweet cakes would be nothing. The god of the second stocking. The goddess of the moment before a sneeze. The small god who keeps the food warm under a cloth. He adds a new one every few weeks, and the dolls keep getting smaller, because his pockets are full.",
"<em>Praise not the great gods,</em> he says. <em>They do not need your prayers. Praise the little ones, whose names you never knew.</em> The priests on either side of him have stopped arguing. Every evening a few people pause in front of him, buy nothing, and go home a little more careful with the lemons."
]},
{ id:"delera-watch", cat:"dead", place:"delera-watch", title:"Delera's Watch", body:[
"In Respite there are more dead than living, and they lie on three floors. On the top floor are the tombs of Delera's Watch, where Storm Lords, pirate captains and rich explorers lie with their treasure and their maps behind traps and wards, because the pirates meant to keep what they had taken. Around those tombs the poor have buried their own for generations, in shallow graves or in the open for the birds, as their customs require, so that the necropolis of the rich stands in a moat of bones. Under all of it lie the barrows of the giants, and under the barrows, the people of Respite say, pits of dead who have lain undisturbed for forty thousand years.",
"The floors do not stay apart. The dead rise here more often than they should, and the newer tombs are warded to keep their occupants in. When House Jorasco tried to raise Delera Omaren herself, a founder of the city, the woman who sat up on the slab cried out in the language of the giants and killed dozens with lightning before she could be put back. Since then the healers of Respite cast an augury before they raise anyone, and they ask it first of all which floor the answer is coming from."
]},
{ id:"crypt-of-the-guard", cat:"dead", place:"crypt-of-the-guard", title:"The Crypt of the Guard", body:[
"The Crypt of the Guard keeps the hours of the tide. It was dug a century ago for the fallen of the Stormreach Guard, a few yards too close to the water, and twice a day the sea fills its vaults to the lintels and the dead are left alone. Twice a day it drains through the cracks, and for about an hour you may walk the aisles in water to the ankle, among crabs.",
"Each slab carries two names, the one the guard signed away and the one he took. The masons cut the old name shallower, as the custom was, and the sea has been taking it first. In the lowest aisle only the new names are left. In the highest both can still be read, and you may learn who each man had been before he joined, though not which of them were the traitors and which the heroes; the men who knew that are in the walls themselves.",
"The Emerald Claw has come more than once at low water and left with soldiers. The living guards save from their pay to be buried anywhere else, and the crypt takes paupers now, who come with one name each. When the tide turns a keeper walks the aisles with a lantern, ahead of the water. He does not read the walls. He counts the slabs that still have two names on them, and writes the number in a book, and every year the number is smaller."
]},
{ id:"old-catacombs", cat:"dead", place:"old-catacombs", title:"The Old Catacombs", body:[
"Near the wall between the Marketplace and Dannel's Pride, the top of a giant's tower juts out of the street at an angle, with the rest of it buried. The servants of the Silver Flame once used it as a sanctuary and a prison. Five years ago the dead came up through it. Most were destroyed. The rest were sealed into the lower floors behind wards and new stone, and the upper floors were abandoned.",
"Beside the sealed door a dwarf smeared with ash beats a drum day and night and recites the names of the dead. He is Yannick Drumdoom, and he serves the Keeper. He collects tokens from tombs, a ring, a buckle, a curl of hair folded in paper, so that their owners will stay close to the world. People cross the street to avoid him. I stood and listened for most of an hour and he did not repeat a name, and when he stopped to drink I asked where he found so many. He pointed down with the drumstick. Then he began again, and the beat followed me across the Marketplace, a little slower than my heart, and that night in my lodging I found I was counting it."
]},
{ id:"floating-ruins", cat:"sky", place:"floating-ruins", title:"The Floating Ruins", body:[
"Once there were fortresses in the air above this city, and mansions, and towers that floated. Time and war broke them, and their pieces still hang over the streets. Some never move. Others drift on slow circuits that the old people know the way fishers know tides, and in Respite there are households that keep their days by them. The broken balcony crosses the sun at the hour for bread. The cistern-stone shades the Garden of Respite at noon, and is blessed for it in summer and cursed for it in winter. The long stone the children call the Boot comes round every nineteen days and blots out the moon over Stormhaven for a night, and on those nights the rich lock their doors.",
"A few wealthy families have patched the larger fragments and live on them. The poor hang wooden houses from the undersides of smaller ones and climb up by knotted rope. The prettiest have gathered the droppings of seabirds for centuries until a seed took, and then another, and now islands of flowers ride over Respite with their roots trailing in the wind. When the wind turns, petals come down on the funerals in Delera's Watch, and the mourners look up and are not sure whom to thank."
]},
{ id:"falconers-spire", cat:"sky", place:"falconers-spire", title:"Falconer's Spire", body:[
"The weather of one month, as the fishers of the Folly chalked it on a beam in the Leaky Dinghy.",
"<em>Sul. Rain from the south. Mol. Rain. Zol. Hail at noon, two boats stove in at their moorings, the Lyrandar ships beside them untouched. Wir. Calm. Zor. Calm, and a squall out of a clear sky off the Talon, one boat lost with three. Far. Fog. Sar. Fog. Second week. Fair wind for three days, the week the Marketplace merchants signed their new contracts with Lyrandar. Lightning twice on one roof in Cross, the roof of a man who had not signed. Rain. Rain.</em>",
"Beside some of the days a fisher has chalked a mark that means <em>honest</em>. Beside most there is nothing.",
"The spire of House Lyrandar rises out of the Marketplace, taller than the palace, inlaid with blue and hung with moored airships. In its highest room an old half-elf named Calynden, whom his own house calls the Kraken because he is not seen until he strikes, reads the reports from the harbor and then closes his eyes over a chart of the Thunder Sea and feels for the paths of the storms. His house once sold fair weather in Khorvaire, to farmers and to generals. In Stormreach it has never been proved to sell anything of the kind. On the beam in the Dinghy the second month is already begun, in a different hand."
]},
{ id:"lighthouse", cat:"sky", place:"lighthouse", title:"The Lighthouse", body:[
"The lighthouse has no stairs. It was raised on its rock in the harbor nearly as long ago as the Emperor, and it is stone the whole way up, and at the top a crystal that no hand has touched turns by itself, sending its beam out over the sea, then back across the roofs of the city, then out again.",
"Only the ground floor and the cellars are hollow, and Eldamir Fallowcrest has filled them with books. You may read one at a time. He stands at your shoulder while you do it, close enough that you hear him breathe, and when you turn a leaf he watches the leaf and not you. At the first sign of trouble he locks the library and sets its traps, and he alone decides what the first sign was.",
"I read a sailing almanac there one afternoon. At dusk the crystal began to turn, and its beam came in through the one high window and crossed my page, and went, and came again. Each time it crossed, Eldamir's lips moved. When I gave the book back I saw on its flyleaf a column of small strokes in his hand, tied in bundles of five, running down the page and onto the next, and the last stroke was still wet."
]},
{ id:"scuppers", cat:"storms", place:"scuppers", title:"The Scuppers", body:[
"The giants built drains so large that their rain ran off in an hour. Since then the drains have been choked with rubbish or sealed from below by the things that live in them, and when a storm comes the water has nowhere to go but the streets.",
"So the people of Stormreach build on stilts, and when their own street floods they cut a channel to send the water into the next street. The next street cuts a channel of its own. Every household knows exactly whose door its water goes to and whose water comes to its own door, and a good share of the city's grudges are older than anyone's memory of the channel that started them. Before a storm is over the water has found its way, house by house and grudge by grudge, into a few broad avenues that pour into the harbor. These are called the scuppers, after the holes in a ship's deck. Newcomers drown in them every year, not knowing to keep clear. Nobody designed the system and everybody resents it. The engineers the Storm Lords once sent to replace it went home and reported that it works, which the city was not pleased to hear."
]},
{ id:"burning-titan", cat:"storms", place:"titan-cliffs", title:"The Burning Titan", body:[
"For six days at the end of winter the city builds a giant on the cliffs east of the Lyrandar shipyard. They make it of wicker, wood and oil. Most of Forgelight gets the week off to help. The Phiarlan elves play music day and night. The builders go through dozens of casks of gin, and the titan rises over the sea with its arms lifted.",
"At sundown on the first of Therendor they set it alight. The crowd wears dragon masks and dances all night, because dragons burned the giants' empire to the ground, and this is the festival of that burning. Across the river the giants of Rushemé watch the glow. They find it distasteful and say so to no one.",
"I danced too, behind a paper dragon's face, until the titan's arms fell in and threw sparks out over the water. Then I turned around. Up the coast the Emperor stood on his cliff, lit orange from below and white from his own hands, with his back to all of us, facing the dark sea. A child beside me had turned as well. She looked from the burning giant to the stone one and back again, took off her mask, and then put it on again."
]},
{ id:"shacklebreak", cat:"storms", place:"marketplace", title:"Shacklebreak", body:[
"On the first of Aryth the law stops. For one day no crime short of murder or arson is punished. Most of the Guard stays home. The Storm Lords grant amnesty to a crowd of prisoners, the cells at the Red Ring open, and masks come out of every chest in the city. On Shacklebreak you may smash a shopfront and walk away. You may fight a stranger, or kiss one, or rob one, or all three in that order. You may sing the songs the Swords of Karrn would take a finger for, burn a chair in the middle of the Marketplace, climb the palace railings and shout at the windows. You may not burn a house or kill a man, though every year somebody forgets which day it is. The city remembers that it was a pirate haven before it was a city, and sets this one day aside for the memory. Some of its people call the day a fever, a small dose of the old madness that made the giants turn on one another and end their nation, and they say that one year the dose will be too large. Others call it the only honest day in the calendar. In the morning the shop boards go back up and the Guard returns to collect its bribes, and for a week afterward people in the street look at one another's faces a little longer than usual, trying to fit them to masks."
]},
{ id:"grindstone", cat:"oaths", place:"grindstone", title:"Grindstone", body:[
"Pass through the gate into Grindstone and the air changes. Doors close. Children stop their game to watch you. Only the street vendors meet your eyes. People from other districts walk quickly here, and the people of Grindstone are proud of that.",
"This is the Karrnathi ward, and it is the only place in Stormreach where theft, brawling and indecency are punished. The Swords of Karrn see to it. Steal here and they will take a finger, so that every time you look at your hand you will remember who governs this street. The Guard does not come in without orders. In the middle of the ward a temple stands inside the skeleton of a giants' ruin, grown over with a crimson ivy as tough as armor, and the priestess of the Blood of Vol keeps her rites there in the open, as her people could not at home. Some thugs once tried to rob her in the street, and half the ward stoned them to death. You will be safer in Grindstone than anywhere in the Harbor. You will not feel safer. When you leave by the far gate you will catch yourself counting your fingers, and the people of Summerfield on the other side will smile at you, because they have seen everyone do it."
]},
{ id:"whitewash", cat:"oaths", place:"whitewash", title:"Whitewash and Embers", body:[
"Every morning the magewrights of Oldgate speak a word over the streets and the dust gets up and leaves. The rubble has been carted off, the houses painted, the moss scraped from the giants' stones, and travelers who crossed the sea to see a ruin complain that the district looks newer than the towns they left. At its western end the great inland gate of the giants still stands, unwashed, because no magewright can reach it.",
"Whitewash is the Aundairian half. It burns more everbright lanterns than any other ward in Stormreach, and in its square a fountain cleans whatever is dipped in it, so that the collars of Whitewash are the whitest in the city and its people know it. Embers is the Thrane half. It keeps to its houses and its prayers and to Commander Valen Vanatar, whose Knights advise Karrns, and anyone who prays to the Six, to walk around.",
"Aundair and Thrane made peace at Thronehold two years ago, on the other side of the sea. The treaty was read aloud on both sides of the street that divides the wards, and both sides went home. The Ninth Wands still walk one pavement with war-wands at their belts. The Knights still walk the other. In the morning the street between them is cleaned twice, once by a magewright from Whitewash and once by a magewright from Embers, and each half of Oldgate stands at its windows to see that the other half's magewright does it properly."
]},
{ id:"undercity", cat:"hidden", place:"waterworks", title:"The Waterworks", body:[
"Where the Koronoo meets the harbor, the city's pipes empty into the sea, and behind the pipes and the steam vents stand iron doors, sealed. What follows is a list of what lies behind them, in order of depth.",
"First, the kobolds, who crawled up out of the deep earth some time in the last century. The Guard pays two coppers a hide.",
"Then the sewers of the giants, vaulted like temples and older the farther you go. Then the tunnels of the thri-kreen, cut in curves no human hand would choose and lined with monuments to something they never explained. Then the flooded halls where the sahuagin once built a town in the giants' drains, which the sahuagin of today refuse to speak of. Then the streets of the giants' own city, buried whole and less worn than anything on the surface, with dust on the tables.",
"Under that, the old records say, the wizards of Cul'sir were working on a source of power so great that they never wrote down plainly what it was. Whether they built it or found it is not recorded.",
"A thri-kreen guide took me through the second door and a little way past the third. He had chosen me; that is how it is done with the thri-kreen. He explained nothing. After an hour we came up again into the noise and stink of the harbor, where the fishwives were shouting and a ship was unloading oranges, and everyone on the quay was standing with their full weight on the stones, as if the stones went all the way down."
]},
{ id:"kol-korran", cat:"hidden", place:"kol-korran", title:"The Tower of Kol Korran", body:[
"A great trench marks the place where the giants stopped building, at the eastern edge of the city, and every people after them stopped there too. The ground beyond it is flat and the harbor beside it is deep. House Kundarak bought it outright, every yard from the harbor to the river mouth, and crossed the trench with two stone bridges, and at the far end of them even the Stormreach Guard can be turned away.",
"From the roofs of Silverwall you can see the Tower of Kol Korran, which is a ring. A wall several feet thick runs round it in a perfect circle, and inside the circle there is sky. A single gatehouse, warded on every stone, lets into the courtyard. What stands in the courtyard can be told only by its shadow, which at evening falls across the wall and out onto the street, taller than the wall by a great deal.",
"Three things are known about the tower. The faithful of Kol Korran, god of wealth, came to pray at it in its first months, and the guards at the gate told them it was not a temple. The guards said it was a place where matters of house security were tested. Burglars went to test it in their turn, and none of them has been seen since.",
"The lamps on the two bridges burn all night. In the evening the dwarves walk out across them on business in the city, each with one guard, or two, or three, and at the far end each of them looks back once at the ring of wall, the way a man pats his coat to feel that the purse is there."
]},
{ id:"underharbor", cat:"hidden", place:"shargons-talon", title:"Shargon's Talon", body:[
"The harbor has a floor of streets. Under the moorings, behind curtains of weed and crusts of mussel shell, there are arches and doorways and stairs going down into darker water. The sahuagin live there. They walk the docks in peace when they come ashore, hire on as guides for the crossing, and dine with the Lyrandar viceroy, who speaks with their priests in their own tongue.",
"In the middle of the harbor a slender tower of stone rises out of the water, more like a stalagmite than a building, with flames burning in its narrow windows. It is the temple of the Devourer, and two priests keep it, an elf and a sahuagin. The faithful swim to it. Rowing is permitted, and despised.",
"I swam out on a still morning. Halfway there I put my face in the water and saw the second city under the first, its streets and doorways and the shapes moving in them. The sahuagin teach that the Devourer raised the land out of the sea in a battle at the beginning of the world and will one day draw it all back under. Nobody down there seemed to be in a hurry. I reached the Talon with my lungs burning and held on to its stone, and an acolyte with scales leaned out of a window and regarded me with courtesy, the kind you show a cousin who has done well enough, considering."
]}
];

// Vignettes, part B (factions, Chapters Two to Four)
const CITIES_B = [
{ id:"molous", cat:"memory", place:"molous", title:"Molou's Distillery", body:[
"The smell reaches you before the building does, hot berries and smoke with something sharp beneath, drifting over Cross and the Marketplace on every warm wind. Molou's Distillery makes kuryeva, a gin of jungle berries drunk in every port of southern Khorvaire. When the pirates of the Thunder Sea made their peace with Galifar, the other captains brought ships and swords to the bargain. Molou Lassite brought casks, and many say he bought the peace with them. A century later, when word came that King Jarot was dead and Galifar had broken into civil war, the Lassite of the day poured a free shot for anyone who would drink to the kingdom's fall, and the line ran down to the docks.",
"Now the distillery also sells sooka, kuryeva with a little dreamlily in it, which goes down gentler and is harder to give up. Lord Varen Lassite buys a drink for anyone who suffers misfortune in the Marketplace, since he cannot always buy them justice, and he throws parties in the taproom that are the only storms anyone in Stormreach looks forward to. I asked a man at the tap what he was drinking to. He considered the question with great care, said it would come to him, and raised the cup anyway."
]},
{ id:"song-and-calling", cat:"desire", place:"harbor-docks", title:"The Song and the Calling", body:[
"A priest of the Sovereign Host who hears it calls it Dol Arrah. A keeper of the Silver Flame calls it the Voice of the Flame. A kalashtar calls it a herald of il-Yannah, the light of the age to come. A shifter from the Sarlonan tundra calls it by a word for wind. A pickpocket in the Harbor has no word for it at all, and stops in the middle of a lift with tears running into his collar. All of them hear a choir, louder when others who hear it are near, and sooner or later all of them buy passage to Stormreach.",
"Others hear a whisper at the edge of sleep, full of a continent they have never seen and a power asleep inside it. They buy passage too.",
"On the docks the choir's people are met by Gilead Rhoy, who floats a hand's breadth above the cobbles on a small carpet with a blanket over his legs, a warforged at one shoulder and a kalashtar at the other. The whisper's people are met, often within the hour, by men and women who give no names and take them below the city. Gilead lost the use of his legs in a room down there, in his first days in Stormreach. He says the whisper is a twisted echo of the Song. Below the city they say the Song is a twisted echo of the whisper.",
"I was told that the two sides have compared, in private, what they hear, and that the descriptions agree. In the mornings the man on the carpet and the people from below wait on the quay a few yards apart. When a passenger comes down the gangplank with that look on his face, they both step forward."
]},
{ id:"kreldo", cat:"signs", place:"cross-hovel", title:"Kreldo", body:[
"No one goes into Xen'drik without reading the omens; it is bad luck to skip them. The city is full of veiled stalls and curtained rooms thick with incense where fortune-tellers will read them for you, and most of the fortune-tellers work for the Hollow Shards. They predict success, because success brings larger tips. A rival who wants you to fail can pay them to predict otherwise.",
"In a hovel in Cross there is one who is different, a hulking hobgoblin who has plainly seen twenty winters and insists that he is eight. He plays on the floor with a wooden lightning rail and a set of toy monsters, chattering to himself. An old half-orc named Skurga, whom some call his nurse and some his wife, takes your coin at the door. Bring him a good wooden toy and he will talk to the spirits. His eyes roll back, his nose bleeds, and a howl comes out of him that belongs to no child. Then he tells you what will happen, and it does. I saw a mercenary captain come out of that hovel white to the lips, walk straight across Cross to the nearest curtained stall, and pay a Shard to tell him something else."
]},
{ id:"black-freighter", cat:"rigging", place:"black-freighter", title:"The Black Freighter", body:[
"The most popular tavern in Southwatch is a ship that has never sailed. It sits on the river on a hull of green stone left by the thri-kreen for a purpose long forgotten, nearly indestructible and buoyant when by rights it should sink. You board by walking a plank. At dawn, when the bar closes, the plank comes in.",
"Inside, the food is what Karrnathi laborers eat, the drink is cheap and steady, and the air is thick with verse, a sea shanty at one table and a slow ballad of the homeland at the next. The proprietor calls himself Captain Smargat, wears a tricorn hat, and greets everyone with the same advice, to be sure they are in the right establishment. Agents of the Emerald Claw drink there openly beside soldiers of the Swords of Karrn, and in the corner a prematurely grey man in white linen sits with a raven on his shoulder. People say the Freighter could slip its mooring and sail downriver whenever it liked. It is fixed to the riverbed. Its floor has hatches that open onto the ruins beneath the city, and on busy nights more people go down through them than come aboard by the plank."
]},
{ id:"night-tide", cat:"trade", place:"harbor-docks", title:"The Night Tide", body:[
"There is a second market in Stormreach, and it has no tent. It takes its name from the days when smugglers came in on the night tide, and it is larger than the black markets of cities three times the size. Nearly everyone in the city uses it, for something, every day.",
"Its tables are never in the same place twice. From them, in a single recent week, a person could have bought Brelish sausages; Aundairian wine; a Siberys shard the size of a gnome's head; a dagger used in blood rites twenty thousand years ago; a potion from the bespectacled gnome who keeps the Pestle and who may, on any given day, poison one for his own amusement; a sword from a dark-haired dwarf missing more fingers than he has left; and anything at all from a fat man with his hair slicked back with whale grease, who calls himself an entrepreneur and cheats on every weight.",
"A relic sold openly in Stormreach pays four parts in ten to the Storm Lords, unless its seller holds a letter of marque, and the rule is applied loosely. The Night Tide pays nothing. Its tables fold at first light, and by the time the bazaar raises its red cloth the Night Tide is a row of empty crates on the quay with gulls standing on them."
]},
{ id:"katanavash", cat:"eyes", place:"riedran-consulate", title:"The Riedran Consulate", body:[
"A short walk from the Wavecrest Tavern lives the consul of Riedra, Lord Katanavash, a handsome man with a mediator's manners. He is one of the Inspired, whose minds are shared with spirits from the realm of dreams. Riedran sailors who put in here see in Stormreach every terrible story they were told about the humans beyond their borders, and they stay aboard. The consul goes ashore. He walks the city in plain clothes and lays his hands on things, old stones, doorposts, the relics explorers bring back, and reads what has happened to them. He will pay well to hold an object from the jungle for an hour. It is said he prefers the past he finds in such things to the present he walks through to reach them.",
"On days when he would rather not be seen, his assistant goes out in his place, wearing his face. She is a changeling named Hope, devoted to the spirit that lives in him, and all twelve of his household know and say nothing. There are mornings when the consul of Riedra is shaking hands in the Marketplace and kneeling in the Harbor with his palm flat on a giant's doorstep, with his eyes closed."
]},
{ id:"iron-watch", cat:"names", place:"iron-watch", title:"The Watch House", body:[
"In Forgelight there is a house where nobody sleeps. Its residents are warforged, built for the Last War, who once served a Brelish commander that spent them like arrows. After seeing one too many comrades shattered, a warforged named Steeljack took his squad, commandeered a boat, and sailed to Stormreach. Lady Paulo Omaren hired them as a counterweight to the family that trains the Guard, and they became the Iron Watch, called out when the Guard meets something it cannot handle. They draw no wages. The gold goes toward a home for their kind.",
"They name their ranks for what they are made of. Wooden Guard. Stone Guard. Iron Guard. Steel Guard. Adamant. Their three Adamants are Steeljack, Smith and Lathe, and of the third it is said that no house in Khorvaire built him. He walked up out of the dungeons beneath the city some time after the Watch was founded, sat down among them, and began teaching the youngest how to knit their own wood back together by thinking about it.",
"At night they stand awake in the street outside their house and watch the windows of the city go dark one at a time. A dockworker told me he would rather have the Karrnathi wolves, because those at least were human. When I repeated this to Steeljack, he agreed that the dockworker was right about the Karrns, and asked me which window was mine, so that they would know when I was asleep."
]},
{ id:"fleas", cat:"dead", place:"the-sloths", title:"The Fleas", body:[
"Within an hour of landing you will meet the Fleas. Six or eight children will surround you, begging for coppers and sweets, crying, laughing, pulling at your sleeve, and when they scatter your purse will go with one of them. They are of every race. There are about forty in all, with dens in the Sloths, in the Harbor and in Locksmith Square, reached through holes too small for you.",
"Their leader is a boy of ten, blackened and swollen, who drowned in the harbor longer ago than anyone remembers. Most believe a guard pushed him in and that his bones are still drifting out there. He has never told his name. The children call him Drifter. He hates grown people, and when a Flea grows up he sends them away, so the gang is always the same age and its members are always new. If you see a young man on the docks watching a ring of children close around a merchant, watching very carefully and helping neither side, he is probably one of those who were sent away. He will not tell you what it was like. He will tell you to mind your purse, a moment too late."
]},
{ id:"shrouds", cat:"dead", place:"twilight-streets", title:"The Shrouds", body:[
"In the red hour before the lamps are lit, a funeral comes down the street with no body in it. The mourners are wrapped in crimson grave-cloth, and where the cloth has slipped their faces are rotten. A shopkeeper who would haggle with any other extortionist sets the coins on the sill and steps back from the window. Living elves cut many of those faces themselves, with scalpels, and blacken the cuts with poison. The rest did not need cutting.",
"At the head walks Whisper, priestess of the Keeper, nearly seven feet tall, in wrappings that smell of perfume and of what the perfume is for. Her brother walks at her side. He was killed in a street fight and came back, and now he goes veiled from crown to foot, and the shopkeepers believe that the face under the veil kills whoever sees it, so they keep their eyes on the coins.",
"A Tharashk inquisitive who examined one of their killings wrote in his report that it was a single step in a ritual that might take a hundred years to finish, and that he could not tell which step. The Shrouds have been destroyed several times in fifty years. Each time, after a season or two, the funeral has come up again out of the tunnels at the red hour, and the next killing has been the next step, counted from where the last one left off."
]},
{ id:"wyrm-ascendant", cat:"sky", place:"sovereign-host", title:"The Temple of the Wyrm Ascendant", body:[
"In the temple of the Sovereign Host in Forgelight, which was built before the city had a Temple district, the gods have wings. The mosaics show them breathing fire on fiends. Dol Dorn over the side altar has a soldier's shield and a long scaled neck, and the mercenaries who kneel to him before a contract do not look up far enough to notice. Over the gate hangs the eight-pointed star, as in any city.",
"The priests teach that the greatest dragons rose into the heavens and became the gods, and that the faithful may rise after them. A dragon does not rise without its hoard. In this congregation, therefore, the devout keep accounts, a fat purse is a sign of grace, and a miracle is priced by the weight of the wound. The deacon who blessed my coins weighed them first in his palm, kindly, and assured me that I was in no danger of heaven yet.",
"The high priest, Maru Sakhesh, was killed by adventurers last year and raised by House Jorasco for a fee, which the temple paid without complaint and entered in the books as an investment. He has looked hard at travelers since. Beneath the floor, the congregation believes, lies a vault holding two centuries of tithes, dragonscale armor stripped from the dead, and a single scale plucked from the hide of Aureon, all guarded by curses. The faithful mean to climb. Every coin they give is carried down the stairs."
]},
{ id:"the-horizon", cat:"storms", place:"southwatch-edge", title:"The Southern Horizon", body:[
"Stand at the edge of Southwatch and turn slowly.",
"To the south, where the jungle meets the sky, a black cloud sits on the horizon and never moves. Sailors steer by it. Inside it, on thunderheads, there is said to be a citadel, and in the citadel a roc grown old and wise who calls himself immortal and has decided that Stormreach is a blight on the land, to be brought down to rubble. The giants of the Tents hold him back with rites and sacrifices. The city does not ask which ones.",
"Inland, less than a day's flight for a dragon, a single sandstone spire rises into a storm that never ends. The blue dragon who lives there is the son of the dragon Delera Omaren killed when the city was a pirate camp. He was young then.",
"Out to sea, a kraken has begun to stir, and the sahuagin have started to say its name. It has never touched a Lyrandar ship.",
"Somewhere in the interior the fire giants of the Basalt Towers, who rained stars on this city in 946 and left craters you can still stand in, are rebuilding. Behind you, as you finish turning, is the city, with its lamps coming on and every head in its streets bent over something nearer."
]},
{ id:"blood-devil", cat:"oaths", place:"marketplace-oath", title:"The Blood Devil", body:[
"Pirates did not trust ink. The only promise a pirate kept was one sworn in blood, and the habit has outlived the pirates. In Stormreach merchants seal contracts by cutting their palms and pressing them together. Brothers swear kinship that way, and lovers on the piers during Pirate's Moon.",
"Everyone knows what happens to someone who breaks such an oath. A hulking red thing comes for him, with a mane soaked in gore and a mouth lined with leeches, and drinks every drop of his blood, since he obviously did not value it very highly. No one claims to have seen it. Everyone knows someone who knew someone who was found white and empty in an alley the week after a deal went bad.",
"The Storm Lords enforce what profits them. The Guard enforces what it is paid to. Everything else that is promised in this city, loans between neighbors, debts of honor, the shares of a find divided at a jungle campfire, is kept by a creature that may not exist and cannot be bribed, and on the whole it is kept well. I shook hands on a small loan in Cross. The man looked at my unscarred palm with pity and named a higher rate."
]},
{ id:"ivory-horn", cat:"oaths", place:"red-ring", title:"The Ivory Horn", body:[
"The greatest fighters of the Red Ring swear themselves to it for life. They take a blood oath to a stablemaster, and they wear his brand and an iron collar until they die. You are god and slave both, one of them told me. A dog on a leash in the street. The center of the world on the sand.",
"Three stablemasters sit on the Blood Council. The first, Malketh Zolark, wears only grey and black, hates color, and keeps more than thirty championship belts over his hearth; his father died in circumstances that are discussed only in whispers. The second, Ralzina Voraal, wears silk in green and red and believes the sigil she burns into her fighters will deliver their souls to her when they die, so she sends them to die with some enthusiasm. The third is Kolos, a minotaur with crimson fur and polished horns, who was a slave in this arena and fought his way to freedom and to a seat at the same table. His stable owns no slaves and shares every purse.",
"He dresses as the other two do, in an aristocrat's finery. Up close the velvet is patched and the buttons are missing, because his money goes to his fighters. On his forearm he leaves bare the brand of a stable that no longer exists, and he shows it to anyone who asks and to many who do not. The crowds who come to watch men sign their lives away cheer him louder than anyone."
]},
{ id:"travelers-inn", cat:"hidden", place:"travelers-inn", title:"The Traveler's Inn", body:[
"One of the inns of Stormreach is a temple, and nothing about it says so. It has a sign, a common room, a hearth, beds of the usual quality, and staff who are pleasant to you. The other guests are sailors, scholars and adventurers. The god it serves is the Traveler, the one with many faces, and its staff and many of its regulars have given themselves to changing the life of anyone who walks in.",
"You will not notice it begin. A conversation at the next table will turn out to concern you. An old map will turn up in a crack between the floorboards of your room. A long-lost relative will take the room across the hall. A merchant will offer you an object of unexplained power at a reasonable price. Or, a few days after you settle the bill and leave, you will be arrested for a terrible crime you did not commit.",
"Nobody can tell you which inn it is. There is a proverb from Sarlona about the Traveler's gifts, and every people in the harbor has its own version. You have slept somewhere since you landed. Think about the faces in the common room this morning, and whether one of them looked at you a moment longer than it needed to, and whether, since then, you have felt any different."
]}
];

// Vignettes, part C
const CITY_EXTRA = [
{ id:"blackbriar", cat:"hidden", place:"blackbriar", title:"Blackbriar", body:[
"North of the city, along the coast, lies a field of black briar that cannot be crossed. It is waist-high at the road and higher as you go in, until it closes over your head, and then, at a certain point, it stops all at once, and you are standing in grassy hills with a manor at their center and a dirt path leading to it. That is, if House Vadalis wants you there. The ranch is the largest holding of any house in Xen'drik, and the briar grows and shrinks at the housemaster's wish. A servant meets visitors at the road with grave warnings about straying. Those the house has not invited walk into the thorns and come out somewhere else, scratched and puzzled, having found nothing.",
"The house's founder in Xen'drik was trampled to death by one of his animals shortly after the war ended. Few ask how. The workers are sworn to secrecy and will hint, at most, that they were hired to bring exotic beasts out of the interior. I stood at the edge of the field one evening with no wind blowing and watched the thorns nearest the road lean slowly toward me, and then, having apparently considered me, lean away."
]}
];

// Night frames: the traveler and the Emperor
const FRAMES = [
{ title:"The First Night", body:[
"On the cliffs above the harbor of Stormreach stands a giant of stone with its palms pressed together and a column of light rising out of its hands. It faces the sea. It has faced the sea for forty thousand years, and it has never seen the city at its back.",
"I climbed up to it on my first night, because there was nowhere else in Stormreach where a stranger could sit without being robbed, and because I had no one else to tell, I began to describe to it what I had seen that day. After a long while the stone answered. The voice came up through the rock like the tide moving in the caves below the Wavecrest Tavern, and each word took as long as a wave to finish.",
"<span class=\"v\">The Emperor:</span> You are very small, and you came from behind me. Nothing comes from behind me. Is my city still there?",
"<span class=\"v\">The traveler:</span> There is a city behind you, Majesty. Whether it is yours, I cannot say. I will tell you what I find in it.",
"<span class=\"v\">The Emperor:</span> Tell it slowly. The sea has said the same thing to me for forty thousand years. I had forgotten that anything else could be said."
]},
{ title:"The Second Night", body:[
"<span class=\"v\">The Emperor:</span> You spoke of rope. Of tents, and driftwood, and a ward where people buy the pieces of a dead country. My city was stone. Its stairs were cut for my feet, and each step was the height of your whole body. You are describing some other city.",
"<span class=\"v\">The traveler:</span> I am describing the only one there is. Yours is under it, in pieces. The ropes are tied to it. The tents are pitched in its doorways. Your stairs are still there, Majesty. The people have cut smaller stairs into them.",
"<span class=\"v\">The Emperor:</span> Into my stairs.",
"The giant was silent for so long that I thought it had finished with me. The beam from its hands went on pouring into the clouds. Below us a bell was ringing in the harbor, and somebody was singing in a language I did not know.",
"<span class=\"v\">The Emperor:</span> How small are the smaller stairs?"
]},
{ title:"The Third Night", body:[
"<span class=\"v\">The Emperor:</span> I have been counting. Of every district you describe, you begin with what it lacks. A country. A name. A drain that works.",
"<span class=\"v\">The traveler:</span> That is how Stormreach receives you. Other ports show you the palace first. Here you are shown the hole where something used to be, and afterwards the people who have moved into it.",
"<span class=\"v\">The Emperor:</span> There is a hole where I used to be. What moved into it?",
"<span class=\"v\">The traveler:</span> Pirates, Majesty. Then their grandchildren. Then everyone else.",
"<span class=\"v\">The Emperor:</span> I do not know the word pirate. Is it a kind of giant?",
"<span class=\"v\">The traveler:</span> It is a kind of everyone."
]},
{ title:"The Fourth Night", body:[
"<span class=\"v\">The Emperor:</span> How long do your kind last?",
"<span class=\"v\">The traveler:</span> Sixty years, if we are lucky. Seventy.",
"<span class=\"v\">The Emperor:</span> Since the light was put in my hands the shore has come toward me four times and gone back three. I have watched one island rise out of the sea and two go under it. Your whole life would pass while I decided whether a wave was large.",
"<span class=\"v\">The traveler:</span> Then you had better listen quickly, Majesty.",
"The light in the giant's hands flickered, as if something far down in the stone had found this funny. Then it asked me to tell it again about the woman with the rag and the bowl who cleans the moss from the stone heads, and I told it twice, and the second time it interrupted to ask what a pickled apple was."
]},
{ title:"The Fifth Night", body:[
"That night the wind came off the land, and with it the smell of the fires on the eastern cliffs, where the city was building something tall out of wicker.",
"<span class=\"v\">The Emperor:</span> I smell burning. I remember fire coming down out of the sky. I remember the dragons. Are they burning us again?",
"<span class=\"v\">The traveler:</span> Only the people of the city burn you now, Majesty, once a year, in wicker, wearing dragon masks. They do it for the pleasure of it. They do not know whom they are burning.",
"<span class=\"v\">The Emperor:</span> Then the dragons won the war and the festival both. They have taught you to dance at it.",
"I had no answer to that, so I told it about the Red Ring instead. It listened to the end, and then asked who had won, and when I did not know, it was quiet for a long time, as if it were working out the odds."
]},
{ title:"The Sixth Night", body:[
"It was Pirate's Moon. All evening the people of the city had been walking out to the ends of the piers and throwing bread and rings and unsent letters into the harbor, and from the cliff we could hear each one go in.",
"<span class=\"v\">The traveler:</span> I have been wondering what you were set here to guard against. The scholars say the demons of the past. The fishers say the sea.",
"<span class=\"v\">The Emperor:</span> I was set here to face whatever came. Nobody told me it would come from behind, on foot, a few at a time, with rope and hammers and songs. I watched the sea for an enemy for forty thousand years. The enemy moved in behind me and opened a tavern.",
"<span class=\"v\">The traveler:</span> Several taverns, Majesty. One of them floats.",
"<span class=\"v\">The Emperor:</span> Tell me about the one that floats.",
"So I told it about the Black Freighter, and the plank drawn in at dawn, and the hatches in its floor. It asked me where the hatches led. Before I could answer it said that it did not want to know, and the beam in its hands narrowed, the way an eye narrows."
]},
{ title:"The Seventh Night", body:[
"The Emperor wished to understand the city by its rules, as a king understands a game by its pieces. I told it that Stormreach has one law, which is to make no trouble for the Storm Lords. Everything else is permitted, or bought.",
"<span class=\"v\">The Emperor:</span> Then I need only understand the five lords, and I will understand the city.",
"<span class=\"v\">The traveler:</span> The people here play a card game called Three-Dragon Ante. Meeting a guard, they say, is like a blind draw, which turns up the platinum dragon one time and the Fool the next. The lords are the same. Each is said to have a second face. One of them, the rumor goes, is a fiend who has watched this coast for fifty thousand years and plays at politics to pass the time.",
"<span class=\"v\">The Emperor:</span> Fifty thousand. Then he was here before me.",
"<span class=\"v\">The traveler:</span> Then he has been behind you the whole time.",
"Deep in the cliff there was a sound I had not heard before, like a millstone starting to turn. Grit ran down the statue's shoulders in a thin stream. The beam swung a hand's width off true, wavered, and came back. Down in the harbor a few lamps went on in windows, as if people had felt something through their beds. The giant did not speak again that night."
]},
{ title:"The Eighth Night", body:[
"A hard storm came in that night, and I sat in the lee of the giant's knee with the rain going past me sideways. The lightning found the spire in the Marketplace twice, and the giant not at all.",
"<span class=\"v\">The traveler:</span> There is an old hill giant who sells fruit and herbs at a tent by the city gate. His grandmother came to the pirates when they first landed and warned them that the land was cursed. They laughed at her. He still repeats her warning to anyone who buys from him, and they still laugh.",
"<span class=\"v\">The Emperor:</span> My people. However small they have become. What will they do when the city falls?",
"<span class=\"v\">The traveler:</span> Nothing to stop it. They have given up trying to save Stormreach. They watch it, they keep a record of its folly, and they mean to see that whatever it lets loose does not spread beyond this coast.",
"<span class=\"v\">The Emperor:</span> Then they are my children. That is exactly what I am doing.",
"<span class=\"v\">The traveler:</span> Is it, Majesty? You watch the sea. They watch the city.",
"The light in its hands dimmed and brightened, slowly, three times, like a long breath drawn and let go.",
"<span class=\"v\">The Emperor:</span> That is a fine distinction, for something that will last seventy years."
]},
{ title:"The Ninth Night", body:[
"<span class=\"v\">The traveler:</span> Tonight I would like to tell you what lies under the city. I went down past the Waterworks, through the iron doors.",
"<span class=\"v\">The Emperor:</span> Do not. I know what is beneath. I knew it when they carved me. The wizards of my city reached for it, and when they understood what they had reached, they set me on this cliff and turned me to the sea, so that whatever stood here would always be facing away from it.",
"<span class=\"v\">The traveler:</span> Why away?",
"<span class=\"v\">The Emperor:</span> Some things grow when they are looked at.",
"The light in its hands burned very steadily that night, and very bright. Below us it was Shacklebreak, and bonfires were going in the Marketplace and masks in every street, and the noise came up the cliff in gusts. I did not describe the undercity. I described the bonfires instead, and a market, and a dwarf drumming the names of the dead, and the giant listened as though each of these were a stone being laid on top of something it did not want to wake."
]},
{ title:"The Tenth Night", body:[
"<span class=\"v\">The Emperor:</span> You have described a city of rope tied to my bones and laid over a thing I was carved to ignore. Why does anyone stay?",
"<span class=\"v\">The traveler:</span> I asked them. Most could not go anywhere else. Some were exiled. Some are waiting for a war to start again. Some are here for one more expedition, and have been for thirty years.",
"<span class=\"v\">The Emperor:</span> And you will go. Your kind always goes.",
"<span class=\"v\">The traveler:</span> At the end of the season, Majesty.",
"<span class=\"v\">The Emperor:</span> Then before you go, tell me the last of it, and tell me what you would do in my place. I have stood in this place for forty thousand years, and no one has ever told me what they would do in it."
]}
];

const EPILOGUE = { title:"Before Dawn", body:[
"<span class=\"v\">The Emperor:</span> You have told me the last of it. Now tell me the other thing. What would you do in my place?",
"<span class=\"v\">The traveler:</span> Turn around, Majesty.",
"<span class=\"v\">The Emperor:</span> You heard what I told you. Some things grow when they are looked at.",
"<span class=\"v\">The traveler:</span> Then look at the roofs. To see what is under the city you would have to look through it. Through the ropes and the laundry and the stilts, through the red tent and the tavern that floats, through a woman cleaning the eyes of a stone head and a dwarf counting out the dead on his drum. They are in the way, Majesty. They have been in the way for two hundred years without knowing it, and nothing older than themselves has ever looked at them.",
"The giant did not answer. Below us the first boats were going out. The beam in its hands grew pale against the sky, as it does every morning. Then came the sound I had heard only once before, the millstone deep in the cliff, very slow, and a thin stream of grit ran down from the great shoulders and scattered in the grass. In that grey light I would swear, and have sworn since in every port, that the stone head had turned, a very little, toward the city."
]};
